blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions & Discussions
    url: https://github.com/programmersd21/velvet/discussions
    about: Ask questions, show off your customized rices, share custom scripts, or seek general system-specific support here!
