name: Release Zip

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Zip
        run: git archive --format=zip HEAD -o release.zip

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(cat version.txt | tr -d '\n')

          gh release create "$TAG" release.zip \
            --title "$TAG" \
            --notes "Auto release"
            
